version: "3.8"

services:
  backend:
    build:
      context: .
    container_name: portfolio-backend
    depends_on:
      - db
    environment:
      # - DATABASE_URL=postgresql://postgress:l1zGQr2CCfLS5cHAsW2RJtw6qX2ZnzWN@dpg-cu1u8e8gph6c73eleuv0-a.oregon-postgres.render.com/portfolio_9h8r
      - DATABASE_URL=postgresql+asyncpg://postgres:1234@db:5432/portfolio

    ports:
      - "8000:8000"

  db:
    image: postgres:15
    container_name: portfolio-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
