version: "3.8"

services:
  backend:
    build:
      context: .
    container_name: portfolio-backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://portfolio_jw0o_user:GMnjMW4qJqa1qds5l9PAOCKnF576rMNm@dpg-d1q3m33uibrs73eapbv0-a.oregon-postgres.render.com/portfolio_jw0o?sslmode=require
      
      # - DATABASE_URL=postgresql+asyncpg://postgres:1234@db:5432/portfolio

    ports:
      - "8000:8000"

  db:
    image: postgres:15
    container_name: portfolio-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
